name: Deploy
description: Create and deploy packages
runs:
  using: composite
  steps:
    - name: Create packages
      shell: bash
      env:
        BUILD_ARCHITECTURE: ${{ matrix.platform.arch }}
        BUILD_CONFIGURATION: ${{ matrix.config }}
      run: python3 conan.py --ci-steps
    - name: Deploy artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}-${{ matrix.config }}-${{ matrix.platform.arch }}
        path: |
          ~/.conan/data/*/*/*/*/export/
          ~/.conan/data/*/*/*/*/package/
          ~/.conan/data/*/*/*/*/metadata.json
