name: Deploy
on:
  push:
    branches:
      - main
jobs:
  macos:
    name: macOS (Apple Clang 12)
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github-actions/platforms/macos-apple-clang
      - name: Build and Deploy
        uses: ./.github/deploy
  ubuntu:
    name: Ubuntu (GCC 9)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github-actions/platforms/ubuntu-gcc
        with:
          dependencies: libgl-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - name: Build and Deploy
        env:
          BUILD_STDLIB: libstdc++11
        uses: ./.github/deploy
  windows:
    name: Windows (MSVC 16)
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github-actions/platforms/windows-msvc
      - name: Build and Deploy
        uses: ./.github/deploy
